# Logstash Configuration for Hybrid IDS

http.host: "0.0.0.0"
path.config: /usr/share/logstash/pipeline
path.logs: /var/log/logstash

# Pipeline settings
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

# Queue settings
queue.type: memory
queue.max_bytes: 1gb

# Monitoring
xpack.monitoring.enabled: false

# Logging
log.level: info
